[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "frontend/netlify/functions" # Matches your site settings

[[functions]]
  path = "ping-db.js" # File inside frontend/netlify/functions/
  schedule = "*/10 * * * *" # Runs every 10 minutes
