[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[scheduled_functions]]
  path = "/netlify/functions/ping-db"
  schedule = "*/10 * * * *"
